#%RAML 1.0 Trait
description: Client id and client secret to be sent in each Request while calling the customer API
headers:
  client_id:
    type: string
    required: true
  client_secret:
    type: string
    required: true
responses:
  401:
    description: Unauthorized or Invalid client
  500:
    description: Bad Response or Internal Server Error